# Generated by Django 3.0.5 on 2020-04-21 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID duy nhất cho bài đăng tin này trong                                         cả cơ sở dữ liệu', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Nhập ngắn gọn nội dung nhà bạn cho thuê', max_length=200)),
                ('province', models.CharField(help_text='Tỉnh, thành phố', max_length=100)),
                ('district', models.CharField(help_text='Quận, huyện', max_length=100)),
                ('locationDetail', models.CharField(help_text='Số nhà, tên đường, ...', max_length=200)),
                ('price', models.IntegerField(help_text='Giá cho thuê mỗi tháng,                                 tối đa 5 triệu')),
                ('area', models.IntegerField(help_text='Tổng diện tích cho thuê                                 (phòng ngủ, vệ sinh, ...) bằng mét vuông')),
                ('livingroomImage', models.ImageField(upload_to='findrooms/media')),
                ('content', models.TextField(help_text='Miêu tả cụ thể nội dung nhà bạn cho thuê', max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
