# Generated by Django 3.0.5 on 2020-04-20 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HouseOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VisitPerDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='HouseAd',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID duy nhất cho bài đăng tin này trong                                         cả cơ sở dữ liệu', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Nhập ngắn gọn nội dung nhà bạn cho thuê', max_length=200)),
                ('province', models.CharField(help_text='Tỉnh, thành phố', max_length=100)),
                ('district', models.CharField(help_text='Quận, huyện', max_length=100)),
                ('locationDetail', models.CharField(help_text='Số nhà, tên đường, ...', max_length=200)),
                ('price', models.IntegerField(help_text='Giá cho thuê mỗi tháng,                                 tối đa 5 triệu')),
                ('area', models.IntegerField(help_text='Tổng diện tích cho thuê                                 (phòng ngủ, vệ sinh, ...) bằng mét vuông')),
                ('livingroomImage', models.ImageField(upload_to='houseAds')),
                ('bathroomImage', models.ImageField(upload_to='houseAds')),
                ('houseImage1', models.ImageField(upload_to='houseAds')),
                ('houseImage2', models.ImageField(upload_to='houseAds')),
                ('houseImage3', models.ImageField(upload_to='houseAds')),
                ('houseImage4', models.ImageField(upload_to='houseAds')),
                ('content', models.TextField(help_text='Miêu tả cụ thể nội dung nhà bạn cho thuê', max_length=1000)),
                ('houseOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='findrooms.HouseOwner')),
            ],
        ),
    ]
