# Generated by Django 3.0.5 on 2020-04-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housead',
            name='bathroomImage',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='housead',
            name='houseImage1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='housead',
            name='houseImage2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='housead',
            name='houseImage3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='housead',
            name='houseImage4',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='housead',
            name='livingroomImage',
            field=models.ImageField(upload_to=''),
        ),
    ]
