# Generated by Django 3.0.5 on 2020-04-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('findrooms', '0002_auto_20200420_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housead',
            name='bathroomImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='housead',
            name='houseImage1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='housead',
            name='houseImage2',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='housead',
            name='houseImage3',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='housead',
            name='houseImage4',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
