# Generated by Django 3.0.5 on 2020-04-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findrooms', '0003_auto_20200420_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housead',
            name='bathroomImage',
        ),
        migrations.RemoveField(
            model_name='housead',
            name='houseImage1',
        ),
        migrations.RemoveField(
            model_name='housead',
            name='houseImage2',
        ),
        migrations.RemoveField(
            model_name='housead',
            name='houseImage3',
        ),
        migrations.RemoveField(
            model_name='housead',
            name='houseImage4',
        ),
    ]
